# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{data_fabric}
  s.version = "1.2.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mike Perham"]
  s.date = %q{2010-08-10}
  s.email = %q{mperham@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "CHANGELOG",
     "README.rdoc",
     "Rakefile",
     "TESTING.rdoc",
     "example/Rakefile",
     "example/app/controllers/accounts_controller.rb",
     "example/app/controllers/application.rb",
     "example/app/controllers/figments_controller.rb",
     "example/app/helpers/accounts_helper.rb",
     "example/app/helpers/application_helper.rb",
     "example/app/helpers/figments_helper.rb",
     "example/app/models/account.rb",
     "example/app/models/figment.rb",
     "example/app/views/accounts/index.html.erb",
     "example/app/views/layouts/application.html.erb",
     "example/config/boot.rb",
     "example/config/database.yml",
     "example/config/environment.rb",
     "example/config/environments/development.rb",
     "example/config/environments/production.rb",
     "example/config/environments/test.rb",
     "example/config/initializers/inflections.rb",
     "example/config/initializers/mime_types.rb",
     "example/config/initializers/new_rails_defaults.rb",
     "example/config/routes.rb",
     "example/db/migrate/20080702154628_create_accounts.rb",
     "example/db/migrate/20080702154820_create_figments.rb",
     "example/db/schema.rb",
     "example/public/404.html",
     "example/public/422.html",
     "example/public/500.html",
     "example/public/dispatch.cgi",
     "example/public/dispatch.fcgi",
     "example/public/dispatch.rb",
     "example/public/favicon.ico",
     "example/public/images/rails.png",
     "example/public/robots.txt",
     "example/script/about",
     "example/script/console",
     "example/script/dbconsole",
     "example/script/destroy",
     "example/script/generate",
     "example/script/performance/benchmarker",
     "example/script/performance/profiler",
     "example/script/performance/request",
     "example/script/plugin",
     "example/script/process/inspector",
     "example/script/process/reaper",
     "example/script/process/spawner",
     "example/script/runner",
     "example/script/server",
     "example/test/fixtures/accounts.yml",
     "example/test/functional/accounts_controller_test.rb",
     "example/test/integration/account_figments_test.rb",
     "example/test/test_helper.rb",
     "example23/Rakefile",
     "example23/app/controllers/accounts_controller.rb",
     "example23/app/controllers/application_controller.rb",
     "example23/app/controllers/figments_controller.rb",
     "example23/app/helpers/application_helper.rb",
     "example23/app/models/account.rb",
     "example23/app/models/figment.rb",
     "example23/app/views/accounts/index.html.erb",
     "example23/app/views/layouts/application.html.erb",
     "example23/config/boot.rb",
     "example23/config/database.yml",
     "example23/config/environment.rb",
     "example23/config/environments/development.rb",
     "example23/config/environments/production.rb",
     "example23/config/environments/test.rb",
     "example23/config/initializers/inflections.rb",
     "example23/config/initializers/mime_types.rb",
     "example23/config/initializers/new_rails_defaults.rb",
     "example23/config/locales/en.yml",
     "example23/config/routes.rb",
     "example23/db/development.sqlite3",
     "example23/db/migrate/20080702154628_create_accounts.rb",
     "example23/db/migrate/20080702154820_create_figments.rb",
     "example23/db/s0_development.sqlite3",
     "example23/db/s0_test.sqlite3",
     "example23/db/s1_development.sqlite3",
     "example23/db/s1_test.sqlite3",
     "example23/db/schema.rb",
     "example23/db/test.sqlite3",
     "example23/log/development.log",
     "example23/log/test.log",
     "example23/public/404.html",
     "example23/public/422.html",
     "example23/public/500.html",
     "example23/public/dispatch.cgi",
     "example23/public/dispatch.fcgi",
     "example23/public/dispatch.rb",
     "example23/public/favicon.ico",
     "example23/public/images/rails.png",
     "example23/public/index.html",
     "example23/public/robots.txt",
     "example23/script/about",
     "example23/script/console",
     "example23/script/dbconsole",
     "example23/script/destroy",
     "example23/script/generate",
     "example23/script/performance/benchmarker",
     "example23/script/performance/profiler",
     "example23/script/performance/request",
     "example23/script/plugin",
     "example23/script/process/inspector",
     "example23/script/process/reaper",
     "example23/script/process/spawner",
     "example23/script/runner",
     "example23/script/server",
     "example23/test/fixtures/accounts.yml",
     "example23/test/functional/accounts_controller_test.rb",
     "example23/test/integration/account_figments_test.rb",
     "example23/test/performance/browsing_test.rb",
     "example23/test/test_helper.rb",
     "example23/vendor/plugins/data_fabric/init.rb",
     "example23/vendor/plugins/data_fabric/lib/data_fabric.rb",
     "example23/vendor/plugins/data_fabric/lib/data_fabric/ar20.rb",
     "example23/vendor/plugins/data_fabric/lib/data_fabric/ar22.rb",
     "example23/vendor/plugins/data_fabric/lib/data_fabric/dash.rb",
     "example23/vendor/plugins/data_fabric/lib/data_fabric/version.rb",
     "init.rb",
     "lib/data_fabric.rb",
     "lib/data_fabric/ar20.rb",
     "lib/data_fabric/ar22.rb",
     "lib/data_fabric/dash.rb",
     "lib/data_fabric/version.rb",
     "rails/init.rb",
     "test/connection_test.rb",
     "test/database.yml",
     "test/database.yml.mysql",
     "test/database_test.rb",
     "test/shard_test.rb",
     "test/test_helper.rb",
     "test/thread_test.rb"
  ]
  s.homepage = %q{http://github.com/mperham/data_fabric}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Sharding and replication support for ActiveRecord 2.x}
  s.test_files = [
    "test/connection_test.rb",
     "test/database_test.rb",
     "test/shard_test.rb",
     "test/test_helper.rb",
     "test/thread_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<flexmock>, [">= 0"])
    else
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<flexmock>, [">= 0"])
    end
  else
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<flexmock>, [">= 0"])
  end
end

